version: '3.8'

services:
  crypto-analyzer:
    build: .
    container_name: crypto-analyzer
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge
